//go:build linux

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/containerd/containerd/runtime/v2/runsc/options/oci.proto

/*
   Copyright The containerd Authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package options

import (
	"github.com/containerd/typeurl/v2"
)

func init() {
	typeurl.Register((*Options)(nil), "containerd.runsc.v1.Options")
	typeurl.Register((*CheckpointOptions)(nil), "containerd.runsc.v1.CheckpointOptions")
	typeurl.Register((*ProcessDetails)(nil), "containerd.runsc.v1.ProcessDetails")
}

// Options configures the runsc (gVisor) runtime
type Options struct {
	// Root is the path to the root directory for runsc state
	Root string `json:"root,omitempty"`
	// BinaryName is the binary name or path to the runsc binary
	BinaryName string `json:"binary_name,omitempty"`
	// ShimCgroup is the cgroup path for the shim
	ShimCgroup string `json:"shim_cgroup,omitempty"`
	// IoUid is the uid for the I/O pipes
	IoUid uint32 `json:"io_uid,omitempty"`
	// IoGid is the gid for the I/O pipes
	IoGid uint32 `json:"io_gid,omitempty"`
	// Platform is the runsc platform type (ptrace, kvm, etc.)
	Platform string `json:"platform,omitempty"`
	// Network is the runsc network type (sandbox, host, none)
	Network string `json:"network,omitempty"`
	// Debug enables debug logging in runsc
	Debug bool `json:"debug,omitempty"`
	// DebugLog is the path to debug log file
	DebugLog string `json:"debug_log,omitempty"`
	// CheckpointPath is the path to checkpoint image for restore
	CheckpointPath string `json:"checkpoint_path,omitempty"`
}

// CheckpointOptions for checkpointing a container
type CheckpointOptions struct {
	// Exit the container after a checkpoint
	Exit bool `json:"exit,omitempty"`
	// ImagePath is the checkpoint image path
	ImagePath string `json:"image_path,omitempty"`
	// Compress checkpoint image
	Compress bool `json:"compress,omitempty"`
}

// ProcessDetails contains process-specific information
type ProcessDetails struct {
	// ExecID is the exec process id if the process is managed by a shim
	ExecID string `json:"exec_id,omitempty"`
}
